### ISSUE TITLE
GitHub API limits to 30 releases

### ISSUE THREAD

**Issue by Joe-Brady** [AdoptOpenJDK/openjdk-website-backend#2]
30 release limit:
`https://api.github.com/repos/AdoptOpenJDK/openjdk-nightly/releases`

Increased to 90 release limit through the URL:
`https://api.github.com/repos/AdoptOpenJDK/openjdk-nightly/releases?per_page=90`

The NPM tool has a listReleases function that George is using on the openjdk-website-backend repo (`app.js`):
http://github-tools.github.io/github/docs/3.1.0/Repository.html#listReleases

However, this does not appear to support the same `per_page` option that can be passed in - so we're currently stuck with 30 releases.

Suggested action after discussion: raise an issue on the GitHub repo for the npm tool: https://github.com/github-tools/github/issues

**Comment by karianna** [comment]
@gdams Can be closed now?

**Comment by gdams** [comment]
nope
